# Move palette to the top level
palette = "onedark"

# The format MUST be a single string, not a list
format = """
[](blue)\
$os\
[](bg:cyan fg:blue)\
$directory\
[](bg:magenta fg:cyan)\
$git_branch\
$git_status\
[](bg:white fg:magenta)\
$time\
[ ](fg:white)\
"""

[palettes.onedark]
black = '#282c34'
blue = '#61afef'
cyan = '#56b6c2'
green = '#98c379'
magenta = '#c678dd'
red = '#e06c75'
white = '#abb2bf'
yellow = '#e5c07b'

[os]
disabled = false
style = "bg:blue fg:black"
format = "[$symbol]($style)"

[directory]
style = "bg:cyan fg:black"
format = "[$path]($style)"

[git_branch]
symbol = ""
style = "bg:magenta fg:black"
format = "[[ $symbol $branch ]($style)]"

[time]
disabled = false
time_format = "%R"
style = "bg:white fg:black"
format = "[$time]($style)"

[character]
success_symbol = "[](fg:white) "
error_symbol = "[](fg:red) "
