"$schema" = '[https://starship.rs/config-schema.json](https://starship.rs/config-schema.json)'

format = """
[](base)\
$os\
$username\
[](bg:surface0 fg:base)\
$directory\
[](bg:surface0 fg:surface0)\
$git_branch\
$git_status\
[](fg:surface0 bg:overlay0)\
$conda\
[](fg:overlay0 bg:subtext1)\
$time\
[ ](fg:subtext1)\
$cmd_duration\
$line_break\
$character"""

palette = "deep_one_dark"

[os]
disabled = false
style = "bg:base fg:text"

[os.symbols]
Alpaquita = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
FreeBSD = ""
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
OpenBSD = ""
openSUSE = ""
Raspbian = "󰐿"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = ""

[username]
show_always = true
style_user = "bg:base fg:text"
style_root = "bg:base fg:text"
format = '[ $user]($style)'

[directory]
style = "bg:surface0 fg:blue"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol $branch ](fg:mauve bg:surface0)]($style)'

[git_status]
style = "bg:surface0"
format = '[[($all_status$ahead_behind )](fg:red bg:surface0)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:subtext1"
format = '[[  $time ](fg:crust bg:subtext1)]($style)'

[character]
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'

[palettes.deep_one_dark]
red = "#e06c75"
green = "#98c379"
blue = "#61afef"
mauve = "#c678dd"
text = "#abb2bf"
subtext1 = "#5c6370" 
overlay0 = "#282c34" 
surface0 = "#1c1f24" 
base = "#1
